import type { StarterDeckCard } from "./starter-deck";

// Reviewed category expansion cards generated by scripts/cards:review.
// This starts empty until reviewed candidates are applied.
export const CATEGORY_EXPANSION_DECK: StarterDeckCard[] = [];
