import type { StarterDeckCard } from "./starter-deck";

export const FAMILY_DECK: StarterDeckCard[] = [
  { id: "family-bluey", title: "Bluey", description: "A playful cartoon puppy from the popular family TV show.", category: "fiction_games" },
  { id: "family-spongebob", title: "SpongeBob SquarePants", description: "A cheerful sea sponge who lives in a pineapple under the sea.", category: "fiction_games" },
  { id: "family-minions", title: "Minions", description: "Tiny yellow movie characters known for goggles, bananas, and silly voices.", category: "fiction_games" },
  { id: "family-elsa", title: "Elsa", description: "The Frozen queen with ice powers and a very famous song.", category: "fiction_games" },
  { id: "family-olaf", title: "Olaf", description: "A friendly snowman from Frozen who loves warm hugs.", category: "fiction_games" },
  { id: "family-moana", title: "Moana", description: "A Disney voyager who sails across the ocean to help her island.", category: "fiction_games" },
  { id: "family-mickey-mouse", title: "Mickey Mouse", description: "Disney's classic mouse with round ears, red shorts, and white gloves.", category: "fiction_games" },
  { id: "family-buzz-lightyear", title: "Buzz Lightyear", description: "A Toy Story space ranger who says he is going to infinity and beyond.", category: "fiction_games" },
  { id: "family-woody", title: "Woody", description: "A Toy Story cowboy doll who cares deeply about his friends.", category: "fiction_games" },
  { id: "family-pikachu", title: "Pikachu", description: "A yellow Pokemon with red cheeks and electric powers.", category: "fiction_games" },
  { id: "family-kirby", title: "Kirby", description: "A round pink video game character who inhales enemies and copies powers.", category: "fiction_games" },
  { id: "family-sonic", title: "Sonic the Hedgehog", description: "A super-fast blue video game hedgehog who collects rings.", category: "fiction_games" },
  { id: "family-princess-peach", title: "Princess Peach", description: "The Mushroom Kingdom princess from the Mario games.", category: "fiction_games" },
  { id: "family-luigi", title: "Luigi", description: "Mario's taller green-wearing brother who often gets nervous.", category: "fiction_games" },
  { id: "family-paw-patrol", title: "PAW Patrol", description: "A team of rescue puppies with vehicles and catchphrases.", category: "fiction_games" },
  { id: "family-curious-george", title: "Curious George", description: "A little monkey who gets into trouble by being curious.", category: "fiction_games" },
  { id: "family-cat-in-the-hat", title: "The Cat in the Hat", description: "A Dr. Seuss character with a tall striped hat and chaotic ideas.", category: "fiction_games" },
  { id: "family-winnie-the-pooh", title: "Winnie the Pooh", description: "A gentle bear who loves honey and lives in the Hundred Acre Wood.", category: "fiction_games" },
  { id: "family-peter-pan", title: "Peter Pan", description: "A boy who can fly and refuses to grow up.", category: "fiction_games" },
  { id: "family-pippi-longstocking", title: "Pippi Longstocking", description: "A strong, independent storybook girl with red braids and big adventures.", category: "fiction_games" },
  { id: "family-ms-frizzle", title: "Ms. Frizzle", description: "The magical teacher from The Magic School Bus.", category: "fiction_games" },
  { id: "family-dog", title: "Dog", description: "A loyal pet that barks, wags its tail, and loves walks.", category: "animals_nature" },
  { id: "family-cat", title: "Cat", description: "A curious pet that meows, purrs, and may ignore you completely.", category: "animals_nature" },
  { id: "family-hamster", title: "Hamster", description: "A tiny pet that runs on a wheel and stuffs food in its cheeks.", category: "animals_nature" },
  { id: "family-penguin", title: "Penguin", description: "A waddling bird that swims well and looks like it is wearing a tuxedo.", category: "animals_nature" },
  { id: "family-giraffe", title: "Giraffe", description: "A tall animal with a very long neck and spotted coat.", category: "animals_nature" },
  { id: "family-elephant", title: "Elephant", description: "A huge animal with big ears and a long trunk.", category: "animals_nature" },
  { id: "family-lion", title: "Lion", description: "A big cat often called the king of the jungle.", category: "animals_nature" },
  { id: "family-dolphin", title: "Dolphin", description: "A smart ocean animal known for jumping and clicking sounds.", category: "animals_nature" },
  { id: "family-butterfly", title: "Butterfly", description: "A colorful insect that starts life as a caterpillar.", category: "animals_nature" },
  { id: "family-rainbow", title: "Rainbow", description: "Colorful arcs that can appear in the sky after rain.", category: "animals_nature" },
  { id: "family-volcano", title: "Volcano", description: "A mountain that can erupt with lava, ash, and smoke.", category: "animals_nature" },
  { id: "family-tornado", title: "Tornado", description: "A spinning funnel of wind that reaches from a storm cloud to the ground.", category: "animals_nature" },
  { id: "family-pizza", title: "Pizza", description: "A cheesy food with sauce and toppings, usually sliced into triangles.", category: "places_objects" },
  { id: "family-ice-cream-cone", title: "Ice Cream Cone", description: "A cold treat stacked on a crunchy cone.", category: "places_objects" },
  { id: "family-backpack", title: "Backpack", description: "A bag worn on your back for school, trips, or supplies.", category: "places_objects" },
  { id: "family-bicycle", title: "Bicycle", description: "A two-wheeled ride powered by pedaling.", category: "places_objects" },
  { id: "family-skateboard", title: "Skateboard", description: "A board with wheels used for riding and tricks.", category: "places_objects" },
  { id: "family-treehouse", title: "Treehouse", description: "A small hideout or play space built up in a tree.", category: "places_objects" },
  { id: "family-playground", title: "Playground", description: "A place with slides, swings, climbing bars, and games.", category: "places_objects" },
  { id: "family-library", title: "Library", description: "A quiet place full of books to borrow and read.", category: "places_objects" },
  { id: "family-school-bus", title: "School Bus", description: "A big yellow bus that takes students to and from school.", category: "places_objects" },
  { id: "family-lunchbox", title: "Lunchbox", description: "A container for sandwiches, snacks, and school lunch.", category: "places_objects" },
  { id: "family-night-light", title: "Night Light", description: "A small light that helps a room feel less dark at bedtime.", category: "places_objects" },
  { id: "family-blanket-fort", title: "Blanket Fort", description: "A pretend hideout made from blankets, pillows, chairs, and imagination.", category: "places_objects" },
  { id: "family-bubble-wand", title: "Bubble Wand", description: "A toy used to blow floating soap bubbles.", category: "places_objects" },
  { id: "family-lego", title: "LEGO Bricks", description: "Colorful building bricks used to make almost anything.", category: "places_objects" },
  { id: "family-crayons", title: "Crayons", description: "Coloring sticks used for drawings, posters, and art projects.", category: "places_objects" },
  { id: "family-field-trip", title: "Field Trip", description: "A school outing to a museum, zoo, theater, or other interesting place.", category: "situations" },
  { id: "family-sleepover", title: "Sleepover", description: "Friends staying overnight with snacks, games, and very little sleep.", category: "situations" },
  { id: "family-snow-day", title: "Snow Day", description: "A day when school is canceled because of snow.", category: "situations" },
  { id: "family-lost-tooth", title: "Losing a Tooth", description: "When a baby tooth wiggles out and might earn a visit from the Tooth Fairy.", category: "situations" },
  { id: "family-learning-to-ride-a-bike", title: "Learning to Ride a Bike", description: "Practicing balance, pedaling, and not crashing into the grass.", category: "situations" },
  { id: "family-hide-and-seek", title: "Hide-and-Seek", description: "A game where one person counts while everyone else hides.", category: "situations" },
  { id: "family-musical-chairs", title: "Musical Chairs", description: "A party game where players walk around chairs until the music stops.", category: "situations" },
  { id: "family-pillow-fight", title: "Pillow Fight", description: "A silly battle using soft pillows.", category: "situations" },
  { id: "family-talent-show", title: "Talent Show", description: "A performance where people sing, dance, juggle, or show a special skill.", category: "situations" },
  { id: "family-science-fair", title: "Science Fair", description: "A school event with experiments, posters, and demonstrations.", category: "situations" },
  { id: "family-spelling-test", title: "Spelling Test", description: "A school quiz where you write words correctly.", category: "situations" },
  { id: "family-camping-trip", title: "Camping Trip", description: "Sleeping outdoors with tents, flashlights, snacks, and maybe marshmallows.", category: "situations" },
  { id: "family-choir-concert", title: "Choir Concert", description: "A group singing performance, often with everyone trying to remember the words.", category: "music" },
  { id: "family-recorder", title: "Recorder", description: "A small classroom instrument with a very recognizable squeaky sound.", category: "music" },
  { id: "family-drums", title: "Drums", description: "An instrument you hit with sticks to keep a beat.", category: "music" },
  { id: "family-ukulele", title: "Ukulele", description: "A small string instrument often used for cheerful songs.", category: "music" },
  { id: "family-kidz-bop", title: "KIDZ BOP", description: "Pop songs performed in kid-friendly versions by young singers.", category: "music" },
  { id: "family-school-principal", title: "School Principal", description: "The person in charge of a school.", category: "people" },
  { id: "family-librarian", title: "Librarian", description: "A person who helps people find books and use the library.", category: "people" },
  { id: "family-crossing-guard", title: "Crossing Guard", description: "A person who helps kids cross the street safely.", category: "people" },
  { id: "family-mail-carrier", title: "Mail Carrier", description: "A person who delivers letters and packages.", category: "people" },
  { id: "family-firefighter", title: "Firefighter", description: "A person trained to put out fires and help in emergencies.", category: "people" }
];
