export type StarterDeckCard = {
  id: string;
  title: string;
  description: string;
};

const CORE_DECK: StarterDeckCard[] = [
  { id: "amelia-earhart", title: "Amelia Earhart", description: "A pioneering pilot who became famous for record-setting flights and her mysterious disappearance over the Pacific." },
  { id: "apollo-11", title: "Apollo 11", description: "The NASA mission that first landed humans on the Moon in 1969." },
  { id: "beyonce", title: "Beyonce", description: "A global pop star known for huge concerts, precise choreography, and songs like Single Ladies and Halo." },
  { id: "bigfoot", title: "Bigfoot", description: "A legendary hairy creature said to live in remote North American forests." },
  { id: "bob-ross", title: "Bob Ross", description: "A calm television painter famous for landscapes, soft encouragement, and happy little trees." },
  { id: "cleopatra", title: "Cleopatra", description: "The last active pharaoh of ancient Egypt, remembered for political skill and alliances with Rome." },
  { id: "darth-vader", title: "Darth Vader", description: "The masked Star Wars villain with a deep voice, heavy breathing, and a red lightsaber." },
  { id: "dolly-parton", title: "Dolly Parton", description: "A country music icon, actor, philanthropist, and the creator of songs like Jolene and 9 to 5." },
  { id: "eiffel-tower", title: "The Eiffel Tower", description: "The famous iron landmark in Paris that looks like a giant lattice tower." },
  { id: "elvis-presley", title: "Elvis Presley", description: "The rock and roll singer known for big stage moves, rhinestone jumpsuits, and a huge cultural footprint." },
  { id: "frida-kahlo", title: "Frida Kahlo", description: "A Mexican painter known for vivid self-portraits, flowers, symbolism, and a distinctive personal style." },
  { id: "george-washington", title: "George Washington", description: "The first president of the United States and a general during the American Revolution." },
  { id: "godzilla", title: "Godzilla", description: "A giant movie monster who stomps through cities and blasts atomic energy." },
  { id: "harriet-tubman", title: "Harriet Tubman", description: "An abolitionist who helped enslaved people escape through the Underground Railroad." },
  { id: "hermione-granger", title: "Hermione Granger", description: "The brilliant Harry Potter character known for studying, spells, and helping solve nearly every problem." },
  { id: "jane-goodall", title: "Jane Goodall", description: "A scientist famous for studying chimpanzees and advocating for wildlife conservation." },
  { id: "jaws", title: "Jaws", description: "The shark from the classic thriller movie, usually announced by ominous music." },
  { id: "lebron-james", title: "LeBron James", description: "A basketball superstar known for power, passing, championships, and long-term dominance." },
  { id: "mario", title: "Mario", description: "The mustached Nintendo plumber who jumps on enemies, collects coins, and rescues Princess Peach." },
  { id: "mona-lisa", title: "The Mona Lisa", description: "Leonardo da Vinci's famous portrait with the small mysterious smile." },
  { id: "oprah-winfrey", title: "Oprah Winfrey", description: "A talk show host, producer, and media figure known for interviews and audience giveaways." },
  { id: "picasso", title: "Pablo Picasso", description: "A Spanish artist associated with Cubism and bold, fragmented portraits." },
  { id: "queen-elizabeth-ii", title: "Queen Elizabeth II", description: "The long-reigning British monarch known for formal waves, bright outfits, and royal ceremonies." },
  { id: "serena-williams", title: "Serena Williams", description: "A tennis champion known for power, intensity, and many Grand Slam titles." },
  { id: "sherlock-holmes", title: "Sherlock Holmes", description: "A fictional detective who solves mysteries with sharp observation and deduction." },
  { id: "spider-man", title: "Spider-Man", description: "The superhero who swings between buildings, climbs walls, and says great power brings responsibility." },
  { id: "taylor-swift", title: "Taylor Swift", description: "A singer-songwriter known for eras, devoted fans, and albums that span country, pop, and folk styles." },
  { id: "the-beatles", title: "The Beatles", description: "The British band behind songs like Hey Jude, Yesterday, and Here Comes the Sun." },
  { id: "the-rock", title: "The Rock", description: "Dwayne Johnson, a wrestler turned movie star known for charisma, muscles, and one raised eyebrow." },
  { id: "t-rex", title: "T. rex", description: "A massive meat-eating dinosaur with huge teeth, tiny arms, and a starring role in museum displays." },
  { id: "usain-bolt", title: "Usain Bolt", description: "A Jamaican sprinter famous for world records, Olympic gold medals, and lightning-bolt celebrations." },
  { id: "willy-wonka", title: "Willy Wonka", description: "The eccentric candy maker who runs a fantastical chocolate factory." },
  { id: "yoda", title: "Yoda", description: "The small green Jedi master known for wisdom, unusual sentence order, and teaching Luke Skywalker." },
  { id: "zeus", title: "Zeus", description: "The Greek god of thunder, lightning, and ruling the Olympian gods." },
  { id: "airport-security", title: "Airport Security", description: "The checkpoint routine of bins, scanners, shoes, bags, and hoping nobody forgot a water bottle." },
  { id: "alien-job-interview", title: "An Alien at a Job Interview", description: "A strange visitor trying to explain their skills, work history, and why they are qualified on Earth." },
  { id: "baby-shark", title: "Baby Shark", description: "The children's song with repetitive hand motions that can get stuck in your head instantly." },
  { id: "bad-gps", title: "A Bad GPS", description: "A navigation voice giving directions at exactly the wrong time or sending everyone the wrong way." },
  { id: "birthday-cake", title: "Birthday Cake", description: "A celebration dessert with candles, singing, and someone trying to cut equal slices." },
  { id: "black-friday", title: "Black Friday", description: "The shopping day known for discounts, crowds, carts, and people hunting for deals." },
  { id: "broken-umbrella", title: "A Broken Umbrella", description: "An umbrella that flips inside out, refuses to open, or makes rain feel personally targeted." },
  { id: "cactus", title: "Cactus", description: "A prickly desert plant that stores water and strongly discourages hugs." },
  { id: "celebrity-chef", title: "A Celebrity Chef", description: "A famous cook dramatically tasting food, shouting instructions, or presenting a perfect dish." },
  { id: "coffee-shop-wifi", title: "Coffee Shop Wi-Fi", description: "The shared internet connection everyone needs, often protected by a password on a tiny receipt." },
  { id: "courtroom-objection", title: "Courtroom Objection", description: "A dramatic legal interruption where someone stands up and challenges what was just said." },
  { id: "dad-joke", title: "Dad Joke", description: "A painfully obvious pun delivered with confidence and usually followed by groans." },
  { id: "dance-battle", title: "Dance Battle", description: "A face-off where people answer each other with bigger and stranger dance moves." },
  { id: "dentist-chair", title: "Dentist Chair", description: "The reclining chair where small talk becomes impossible because someone is examining your teeth." },
  { id: "elevator-small-talk", title: "Elevator Small Talk", description: "The awkward conversation squeezed into a short ride between floors." },
  { id: "escape-room", title: "Escape Room", description: "A timed puzzle game where a group searches for clues and overthinks every lock." },
  { id: "family-road-trip", title: "Family Road Trip", description: "A long car ride with snacks, arguments over music, and repeated questions about arrival time." },
  { id: "fashion-runway", title: "Fashion Runway", description: "A dramatic walk showing off clothing while cameras flash and everyone looks serious." },
  { id: "fire-drill", title: "Fire Drill", description: "A practice evacuation with alarms, lines, confusion, and someone still carrying coffee." },
  { id: "fortune-cookie", title: "Fortune Cookie", description: "A crisp cookie with a tiny paper message that sounds wise or oddly specific." },
  { id: "garage-band", title: "Garage Band", description: "A loud beginner band practicing with enthusiasm, questionable timing, and big dreams." },
  { id: "haunted-house", title: "Haunted House", description: "A spooky place full of creaky doors, jump scares, and people insisting they are not scared." },
  { id: "hot-air-balloon", title: "Hot Air Balloon", description: "A floating basket lifted by a huge balloon and bursts of flame." },
  { id: "ice-cream-truck", title: "Ice Cream Truck", description: "A vehicle playing cheerful music while selling frozen treats to a suddenly excited neighborhood." },
  { id: "karaoke-night", title: "Karaoke Night", description: "A public singalong where confidence often matters more than hitting the right notes." },
  { id: "lost-luggage", title: "Lost Luggage", description: "The travel nightmare where your suitcase goes somewhere else and you hope it returns." },
  { id: "magic-trick", title: "Magic Trick", description: "A performance where something disappears, reappears, or makes everyone ask how it happened." },
  { id: "mall-santa", title: "Mall Santa", description: "A holiday photo setup where children meet Santa in the middle of a shopping mall." },
  { id: "mime-stuck-in-box", title: "Mime Stuck in a Box", description: "The classic silent act of feeling invisible walls with exaggerated hands." },
  { id: "office-printer", title: "Office Printer", description: "The machine that jams, beeps, needs toner, and becomes everyone's shared problem." },
  { id: "opera-singer", title: "Opera Singer", description: "A performer using a powerful classical voice that can fill a theater." },
  { id: "parking-ticket", title: "Parking Ticket", description: "The unpleasant slip of paper that says your car sat in the wrong place too long." },
  { id: "pirate-captain", title: "Pirate Captain", description: "A ship leader with treasure maps, dramatic orders, and possibly an eye patch." },
  { id: "pizza-delivery", title: "Pizza Delivery", description: "The hopeful moment when hot pizza arrives at the door, ideally still on time." },
  { id: "prom-posal", title: "Promposal", description: "An elaborate or funny public invitation asking someone to go to prom." },
  { id: "reality-show-villain", title: "Reality Show Villain", description: "The cast member edited to cause drama, deliver suspicious confessionals, and stir the pot." },
  { id: "roller-coaster", title: "Roller Coaster", description: "A fast amusement park ride with climbs, drops, loops, and loud screaming." },
  { id: "school-picture-day", title: "School Picture Day", description: "The annual photo ritual with stiff poses, bright backgrounds, and one chance to smile normally." },
  { id: "secret-agent", title: "Secret Agent", description: "A spy doing missions, hiding gadgets, and acting casual while everything is suspicious." },
  { id: "silent-disco", title: "Silent Disco", description: "A dance party where people wear headphones and the room sounds strange without the music." },
  { id: "speed-dating", title: "Speed Dating", description: "A quick series of mini-dates where people try to make an impression in minutes." },
  { id: "spelling-bee", title: "Spelling Bee", description: "A competition where contestants spell difficult words out loud under pressure." },
  { id: "summer-camp", title: "Summer Camp", description: "A seasonal getaway with cabins, games, songs, activities, and possibly homesick campers." },
  { id: "surprise-party", title: "Surprise Party", description: "A secret celebration where everyone hides, waits, and hopes the guest of honor is actually surprised." },
  { id: "taco-truck", title: "Taco Truck", description: "A food truck serving tacos, usually with a line of people who know exactly what they want." },
  { id: "talent-show", title: "Talent Show", description: "A performance event where people sing, dance, juggle, or reveal unexpected skills." },
  { id: "taxi-driver", title: "Taxi Driver", description: "A driver navigating traffic, routes, passengers, and possibly strong opinions about the city." },
  { id: "tech-support", title: "Tech Support", description: "The person asking whether everything is plugged in and suggesting a restart." },
  { id: "theme-park-map", title: "Theme Park Map", description: "A folded guide that promises clarity while everyone argues about where to go next." },
  { id: "thunderstorm", title: "Thunderstorm", description: "A weather event with rain, lightning, thunder, and dramatic window watching." },
  { id: "time-traveler", title: "Time Traveler", description: "Someone visiting another era and trying not to change history too much." },
  { id: "treasure-map", title: "Treasure Map", description: "A map marked with clues, dotted lines, and an X where riches are supposed to be buried." },
  { id: "trivia-host", title: "Trivia Host", description: "The person reading questions, judging answers, and keeping score during quiz night." },
  { id: "valet-parking", title: "Valet Parking", description: "Handing over your car keys and trusting someone else to park the vehicle." },
  { id: "vending-machine", title: "Vending Machine", description: "A snack machine that sometimes drops treats and sometimes traps them behind the glass." },
  { id: "wedding-dj", title: "Wedding DJ", description: "The music wrangler balancing dance hits, announcements, and someone's very specific song request." },
  { id: "yoga-class", title: "Yoga Class", description: "A group exercise session with poses, breathing, mats, and people trying not to fall over." },
  { id: "zombie-apocalypse", title: "Zombie Apocalypse", description: "A survival scenario with slow monsters, barricades, supplies, and questionable group decisions." }
];

const DRAFT_SUBJECTS = [
  { id: "astronaut", title: "An Astronaut", description: "a space explorer in a bulky suit, dealing with zero gravity and mission control" },
  { id: "baker", title: "A Baker", description: "someone covered in flour, juggling ovens, dough, frosting, and impossible timing" },
  { id: "ballerina", title: "A Ballerina", description: "a graceful dancer trying to keep perfect balance through an inconvenient situation" },
  { id: "barista", title: "A Barista", description: "a coffee expert managing orders, foam, names, and a long line of impatient customers" },
  { id: "bodybuilder", title: "A Bodybuilder", description: "a very strong person who makes even ordinary tasks look dramatic" },
  { id: "camp-counselor", title: "A Camp Counselor", description: "an energetic leader trying to keep campers organized, entertained, and mostly safe" },
  { id: "cat-burglar", title: "A Cat Burglar", description: "a sneaky thief tiptoeing through alarms, windows, and very creaky floors" },
  { id: "celebrity", title: "A Celebrity", description: "a famous person being watched, photographed, and asked for attention everywhere" },
  { id: "cowboy", title: "A Cowboy", description: "a western rider with boots, a hat, and a habit of making things sound rugged" },
  { id: "detective", title: "A Detective", description: "a mystery solver looking for clues, motives, and suspiciously convenient evidence" },
  { id: "dragon", title: "A Dragon", description: "a giant fire-breathing creature trying to behave in a surprisingly normal setting" },
  { id: "flight-attendant", title: "A Flight Attendant", description: "a calm professional explaining rules while everyone tries to board at once" },
  { id: "game-show-host", title: "A Game Show Host", description: "a cheerful announcer turning every small moment into a dramatic reveal" },
  { id: "ghost", title: "A Ghost", description: "a spooky visitor who floats, haunts, and has trouble being taken seriously" },
  { id: "gold-medalist", title: "A Gold Medalist", description: "a champion athlete treating the moment like an Olympic final" },
  { id: "grandma", title: "A Grandma", description: "a loving elder with strong opinions, snacks, and surprising confidence" },
  { id: "hairdresser", title: "A Hairdresser", description: "a stylist handling scissors, gossip, mirrors, and someone's risky new look" },
  { id: "knight", title: "A Knight", description: "an armored hero trying to stay noble while everything gets awkward" },
  { id: "librarian", title: "A Librarian", description: "a quiet authority figure surrounded by books, rules, and whispering" },
  { id: "magician", title: "A Magician", description: "a performer making things vanish, appear, or become unnecessarily mysterious" },
  { id: "pirate", title: "A Pirate", description: "a treasure-hunting sailor with big gestures and questionable table manners" },
  { id: "robot", title: "A Robot", description: "a mechanical helper interpreting human life far too literally" },
  { id: "royal", title: "A Royal", description: "a king, queen, prince, or princess expecting ceremony in an ordinary situation" },
  { id: "scientist", title: "A Scientist", description: "a researcher testing theories, taking notes, and overexplaining the obvious" },
  { id: "superhero", title: "A Superhero", description: "a costumed rescuer with powers, poses, and terrible timing" },
  { id: "tour-guide", title: "A Tour Guide", description: "an enthusiastic narrator trying to keep a group moving and impressed" },
  { id: "vampire", title: "A Vampire", description: "a dramatic immortal avoiding sunlight, mirrors, and suspicious questions" },
  { id: "wizard", title: "A Wizard", description: "a spellcaster with robes, magic words, and unpredictable results" },
  { id: "wrestler", title: "A Wrestler", description: "a showy competitor turning every conflict into a performance" }
] as const;

const DRAFT_ACTIONS = [
  { id: "auditioning-for-a-musical", label: "Auditioning for a Musical", detail: "singing, posing, and trying very hard to land the part" },
  { id: "babysitting-triplets", label: "Babysitting Triplets", detail: "handling three tiny sources of chaos at the same time" },
  { id: "cooking-on-live-tv", label: "Cooking on Live TV", detail: "preparing food while pretending nothing is going wrong" },
  { id: "doing-a-weather-report", label: "Doing a Weather Report", detail: "explaining the forecast with big gestures and questionable confidence" },
  { id: "getting-a-parking-ticket", label: "Getting a Parking Ticket", detail: "reacting to an annoying little paper on the windshield" },
  { id: "leading-a-workout-class", label: "Leading a Workout Class", detail: "counting reps, demonstrating moves, and trying to motivate everyone" },
  { id: "losing-phone-service", label: "Losing Phone Service", detail: "searching for bars and becoming increasingly desperate to reconnect" },
  { id: "ordering-at-a-drive-thru", label: "Ordering at a Drive-Thru", detail: "talking into a speaker that may or may not understand them" },
  { id: "solving-a-mystery", label: "Solving a Mystery", detail: "examining clues and accusing people with dramatic certainty" },
  { id: "trying-to-look-normal", label: "Trying to Look Normal", detail: "acting casual while everything about the situation is obviously weird" },
  { id: "using-a-self-checkout", label: "Using a Self-Checkout", detail: "arguing with a machine about bags, barcodes, and unexpected items" },
  { id: "winning-a-reality-show", label: "Winning a Reality Show", detail: "celebrating for the cameras after surviving manufactured drama" }
] as const;

const EXPANDED_DECK: StarterDeckCard[] = DRAFT_SUBJECTS.flatMap((subject) =>
  DRAFT_ACTIONS.map((action) => ({
    id: `${subject.id}-${action.id}`,
    title: `${subject.title} ${action.label}`,
    description: `${subject.title} is ${action.detail}; think ${subject.description}.`
  }))
);

export const STARTER_DECK: StarterDeckCard[] = [...CORE_DECK, ...EXPANDED_DECK];
